services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    environment:
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.bind_host=0.0.0.0
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: [ "CMD", "curl", "-u", "elastic:searchPathRules", "-f", "localhost:9200" ]
      interval: 30s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    profiles: ["monitor"]
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    profiles: ["monitor"]
    restart: always
    ports:
      - 7081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 9090:8080
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo:27017/gym-tonic?authSource=admin
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_healthy

  vue:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:9090/api/v1/
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 9091:3000
